services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.js:/usr/src/wpp-server/dist/config.js
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"

volumes:
  wppconnect_tokens: {}      